require("user.set")
require("user.manager")
require("user.visual")
require("user.remap")
require("user.treesitter")
require("user.ale")
require("user.rose_pine")
require("user.commands")
require("user.lspconfig")
require("user.hydra")
require("user.custom_functions")
require("user.autosave")
require("user.wrapper")
require("user.ft")
require("user.sessions")
require("user.fzf")

