#!/bin/bash

echo -e "\nChoose an action:\n"
echo "1 - Extract a file"
echo "2 - Compress a file"
printf "\n=> "
read -r action_choice

tar_flags=""
file_path=""

if [ "$action_choice" -eq 1 ]; then
    echo -e "\nYou chose to extract a file. (-x)"
    tar_flags="-x" # Start with extract flag
elif [ "$action_choice" -eq 2 ]; then
    echo -e "\nYou chose to compress a file. (-c)"
    tar_flags="-c" # Start with create flag

    echo -e "\nBy itself tar only combines files into a single file (an archive)
without reducing the size of the files.
    \nUse gzip compression?\n"
    echo "1 - Yes"
    echo "2 - No"
    printf "\n=> "
    read -r gzip_choice

    case $gzip_choice in
        1)
            tar_flags+="z" # Add gzip flag
            ;;
        2)
            ;;
        *)
            echo "Invalid choice"
            exit 1
            ;;
    esac
else
    echo "Invalid choice"
    exit 1
fi

# Request input for the file or directory to process
echo -e "\nEnter the path of the file/directory:"
printf "=> "
read -r file_path
file_path="${file_path/#~/$HOME}" # Expand tilde to home directory

# For compression, ask for the output file name or path
if [ "$action_choice" -eq 2 ]; then
    echo -e "\nEnter the name or path for the output file (e.g., archive.tar.gz or /path/to/archive.tar.gz):"
    printf "=> "
    read -r output_file
    tar_flags+="f" # Add file flag
    tar_command="tar ${tar_flags} ${output_file} ${file_path}"
else
    tar_flags+="f" # Add file flag
    tar_command="tar ${tar_flags} ${file_path}"
fi

# Execute the tar command
echo -e "\nExecuting: $tar_command"
eval "$tar_command"

echo -e "\nDone."

