- name: Configure fresh Arch Linux install
  hosts: localhost
  gather_facts: false
  tasks:
        - name: Synchronize package database and install packages
          community.general.pacman:
            name:
              - package1
              - package2
            state: present
            update_cache: yes
          become: yes

